### ISSUE TITLE
About MVS and MVS-large datasets

### ISSUE THREAD

**Issue by huangmozhi9527** [duyali2000/MQMC#1]
Hi, thank you for sharing your excellent work.
It seems that the released datasets are already extracted features. Could you please share the original data (videos, images and texts)?

**Comment by duyali2000** [comment]
Thanks for your concern! For the protection of user security, we can not release the raw data. But we have publicly released the extracted features of the dataset, which is used in our method. With the codes and public features of raw data, I have full confidence in the reproducibility of our experimental results.
